apiVersion: v1
kind: Service
metadata:
  name: javaline-backend
  namespace: javaline
  labels:
    app: javaline
    component: backend
spec:
  type: ClusterIP
  selector:
    app: javaline
    component: backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
