apiVersion: v1
kind: Service
metadata:
  name: javaline-frontend
  namespace: javaline
  labels:
    app: javaline
    component: frontend
spec:
  type: LoadBalancer
  selector:
    app: javaline
    component: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
