apiVersion: v1
kind: Secret
metadata:
  name: javaline-secrets
  namespace: javaline
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:javaline_secret@javaline-db:5432/javaline"
  SECRET_KEY: "super-secret-key-javaline-2026"
  POSTGRES_PASSWORD: "javaline_secret"
